apiVersion: batch/v1
kind: CronJob
metadata: { name: daily-event }
spec:
  schedule: "0 * * * *"   # hourly sweep to simulate per-timezone
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: sweeper
              image: curlimages/curl:8.9.1
              command: ["sh","-lc","curl -sS -X POST -H 'Authorization: Bearer $CRON_TOKEN' http://api.withme.local/cron/daily_event || true"]
              env:
                - name: CRON_TOKEN
                  valueFrom: { secretKeyRef: { name: withme-secrets, key: CRON_TOKEN } }
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata: { name: semantic-refresh }
spec:
  schedule: "30 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: refresher
              image: curlimages/curl:8.9.1
              command: ["sh","-lc","curl -sS -X POST -H 'Authorization: Bearer $CRON_TOKEN' http://api.withme.local/cron/semantic_refresh || true"]
              env:
                - name: CRON_TOKEN
                  valueFrom: { secretKeyRef: { name: withme-secrets, key: CRON_TOKEN } }
          restartPolicy: OnFailure
