apiVersion: v1
kind: Secret
metadata: { name: withme-secrets }
type: Opaque
data:
  OPENAI_API_KEY: <base64>
  PINECONE_API_KEY: <base64>
  PINE_CONE_API_KEY: <base64>
  FAL_API_KEY: <base64>
  FALAI_API_KEY: <base64>
  SUPABASE_JWT_SECRET: <base64>
  SUPABASE_PROJECT_URL: <base64>
  SUPABASE_ANON_KEY: <base64>
  SUPABASE_SERVICE_ROLE_KEY: <base64>
  SUPABASE_JWT_TOKEN: <base64>
  SUPABASE_DB_PASSWORD: <base64>
  SUPABASE_URL: <base64>
  REDIS_URL: <base64>
  FCM_SERVER_KEY: <base64>
  CRON_TOKEN: <base64>
